---
title: "figure_2_code_share"
output: html_document
date: "2023-02-02"
---

```{r}
#load libraries
library(MutationalPatterns)
library(BSgenome)
library(BiocManager)
library(BSgenome.Mmusculus.UCSC.mm10)
ref_genome <- "BSgenome.Mmusculus.UCSC.mm10"
library(ref_genome, character.only = TRUE)
library(ggplot2)
library(tidyverse)
library(lsa, quietly = TRUE)
```

```{r}
#define metadata (sample names)
sample_names <- c("2_c2", "2_c3", "2_c4", "2_c5",
            "3_c2", "3_c3", "3_c4", "3_c5",
            "15_c1", "15_c2", "15_c3", "15_c4",
            "26_c2", "26_c3", "26_c4", "26_c5",
            "28_c1", "28_c2", "28_c3", "28_c4",
        "17_c1", "17_c2", "17_c3",
         "19_c1", "19_c2", "19_c3", "19_c4",
         "23_c1", "23_c2", "23_c3", "23_c4",
         "24_c1", "24_c3", "24_c4", "24_c5",
         "36_c2", "36_c3", "36_c4", "36_c5"
)

n_sample_names <- c("2_c2", "2_c3", "2_c4", "2_c5",
            "3_c2", "3_c3", "3_c4", "3_c5",
            "15_c1", "15_c2", "15_c3", "15_c4",
            "26_c2", "26_c3", "26_c4", "26_c5",
            "28_c1", "28_c2", "28_c3", "28_c4")

hfd_sample_names <- c("17_c1", "17_c2", "17_c3",
         "19_c1", "19_c2", "19_c3", "19_c4",
         "23_c1", "23_c2", "23_c3", "23_c4",
         "24_c1", "24_c3", "24_c4", "24_c5",
         "36_c2", "36_c3", "36_c4", "36_c5")

#define metadata diet type
diet <- c(rep("normal", 20), rep("high fat", 19))
```

```{r}
#load data
load("~/Desktop/zcan_code/data/snv_grl.RData")
```

```{r}
#count mutations

#channel mutation types
type_occurrences <- mut_type_occurrences(snv_grl, ref_genome)

#96 channel mutation types
mut_mat <- mut_matrix(vcf_list = snv_grl, ref_genome = ref_genome)

```

```{r}
#summary statistics

#section mutation matrix by diet
mut_mat_n <- mut_mat[,c(1:20)]
mut_mat_hfd <- mut_mat[,c(21:39)]

#sum by diet
n_diet_profile = rowMeans(mut_mat_n)
n_diet_profile_sd = apply(mut_mat_n,1,sd)
hfd_diet_profile = rowMeans(mut_mat_hfd)
hfd_diet_profile_sd = apply(mut_mat_hfd,1,sd)
diet_profile = cbind(hfd_diet_profile, n_diet_profile)

#sum by mouse
m2 = rowMeans(mut_mat_n[,c(1:4)])
m3 = rowMeans(mut_mat_n[,c(5:8)])
m15 = rowMeans(mut_mat_n[,c(9:12)])
m26 = rowMeans(mut_mat_n[,c(13:16)])
m28 = rowMeans(mut_mat_n[,c(17:20)])

m17 = rowMeans(mut_mat_hfd[,c(1:3)])
m19 = rowMeans(mut_mat_hfd[,c(4:7)])
m23 = rowMeans(mut_mat_hfd[,c(8:11)])
m24 = rowMeans(mut_mat_hfd[,c(12:15)])
m36 = rowMeans(mut_mat_hfd[,c(16:19)])

n_mice <- cbind(m2, m3, m15, m26, m28)

hfd_mice <- cbind(m17, m19, m23, m24, m36)

mouse_profile <- cbind(hfd_mice, n_mice)
```

# PANEL B
```{r}
panel_b <- plot_spectrum(type_occurrences, by = diet, CT = TRUE, indv_points = TRUE, legend = TRUE)
panel_b <- panel_a + theme(axis.text.y = element_text(size = 12), axis.title.y = element_text(size = 14),
                   title = element_text(size = 14), legend.text = element_text(size = 12))
panel_b
```

# statistical test for panel B
```{r}
type_occurrences$diet <- diet

t.test_1 <- pairwise.t.test(type_occurrences$`C>A`, type_occurrences$diet)
t.test_2 <- pairwise.t.test(type_occurrences$`C>G`, type_occurrences$diet)
t.test_3 <- pairwise.t.test(type_occurrences$`C>T other`, type_occurrences$diet)
t.test_4 <- pairwise.t.test(type_occurrences$`T>A`, type_occurrences$diet)
t.test_5 <- pairwise.t.test(type_occurrences$`T>C`, type_occurrences$diet)
t.test_6 <- pairwise.t.test(type_occurrences$`T>G`, type_occurrences$diet)
t.test_7 <- pairwise.t.test(type_occurrences$`C>T at CpG`, type_occurrences$diet)

print(t.test_1$p.value)
print(t.test_2$p.value)
print(t.test_3$p.value)
print(t.test_4$p.value)
print(t.test_5$p.value)
print(t.test_6$p.value)
print(t.test_7$p.value)

```

# PANEL C 
```{r}
source('~/Desktop/zcan_code/figure2/96_channel_error_bar_functions.R')

panel_c <- add_error_bars(mut_mat, diet_profile ,y_max_param = 0.1)

panel_c
```

```{r}
#export figure to PDF
setwd('~/Desktop')

pdf("Rplot_figure2.pdf", width = 12, height =6,)
plot(panel_b)
plot(panel_c)

dev.off()
```








